spring:
  servlet:
    multipart:
      max-file-size: 10MB
    encoding:
      charset: UTF-8
      force: true
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
  sql:
    init:
      mode: always
      data-locations: classpath:static/data/data.sql
      encoding: utf-8
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
    defer-datasource-initialization: true
  cloud:
    aws:
      enabled: false

server:
  servlet:
    encoding:
      force-response: true

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_BUCKET}
    region:
      static: ${AWS_REGION_STATIC}
    stack:
      auto: false
